config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'queues#dashboard'

  get 'aircraft/enqueue/new' => 'queues#new', as: 'new_aircraft'

  post 'aircraft/enqueue' => 'queues#enqueue', as: 'enqueue'

  delete 'aircraft/dequeue' => 'queues#dequeue', as: 'dequeue'

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  class UnavailableError < StandardError; end

  validates_presence_of :size, :kind
  validates :size, inclusion: { in: %w(small large),
    message: "%{value} is not a valid size." }
  validates :kind, inclusion: { in: %w(passenger cargo),
    message: "%{value} is not a valid aircraft type." }


  def self.enqueue!(options)
    Aircraft.create!(size: options["size"], kind: options["kind"])
  end

  def self.grab_removable_aircraft
    unless aircraft = Aircraft.passenger_ac_available_to_remove? || aircraft = Aircraft.cargo_ac_available_to_remove?
      raise Aircraft::UnavailableError, "There are no aircraft currently queued."
    end
    aircraft
  end

  def self.grab_removable_aircraft_by_size
    Aircraft.large_available_to_remove? || Aircraft.small_available_to_remove?
  end

  def self.grab_removable_aircraft_by_date_queued
    Aircraft.grab_removable_aircraft_by_size.order(created_at: :asc).first
  end

  def self.dequeue_aircraft!
    dequeued_ac = Aircraft.grab_removable_aircraft_by_date_queued
    Aircraft.delete(dequeued_ac.id)
  end

private

  def self.size_options
    ["small", "large"]
  end

  def self.type_options
    ["passenger", "cargo"]
  end

  def self.passenger_ac_available_to_remove?
    available = Aircraft.where(kind: "passenger")
    available if available != []
  end

  def self.cargo_ac_available_to_remove?
    available = Aircraft.where(kind: "cargo")
    available if available != []
  end

  def self.large_available_to_remove?
    dequeable = Aircraft.grab_removable_aircraft
    available = dequeable.where(size: "large") if dequeable.where(size: "large") != []
    available
  end

  def self.small_available_to_remove?
    dequeable = Aircraft.grab_removable_aircraft
    available = dequeable.where(size: "small") if dequeable.where(size: "small") != []
    available
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!


private

  rescue_from StandardError do |e|
    flash[:alert] = "Oops! Something went wrong. Please try again."
    redirect_to :root
  end
  
end

app/controllers/queues_controller.rb
class QueuesController < ApplicationController

  def dashboard
    enqueued = Aircraft.all
    @num_current_cargo = enqueued.where(kind: "cargo").count
    @num_current_passenger = enqueued.where(kind: "passenger").count 
    @num_current_small = enqueued.where(size: "small").count 
    @num_current_large = enqueued.where(size: "large").count
    @aircraft_count = enqueued.count
    
  end

  def new
    @aircraft = Aircraft.new
    @size_options = Aircraft.size_options
    @type_options = Aircraft.type_options

  end

  def enqueue
    if Aircraft.enqueue!(enqueue_params)
      flash[:notice] = "Aircraft enqueued successfully."
    else
      flash[:alert] = "Could not add aircraft. Please try again."
    end
    redirect_to :root
  end

  def dequeue
    begin
      if Aircraft.dequeue_aircraft!
       flash[:notice] = "Aircraft dequeued successfully!"
      end
    rescue Aircraft::UnavailableError => e
      flash[:alert] = "#{e} Unable to dequeue aircraft."
    end
    redirect_to :back
  end

private
  def enqueue_params
    params.permit("kind", "size")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def translate_to_bootstrap flash_class
    case flash_class.to_sym
    when :notice
      :success
    when :alert
      :danger
    else
      flash_class
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AircraftQueuer</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <% if current_user %>
  <div class="container">
      <div class="navbar-right">
       <p>Current user: <%= current_user.email %>
       <%= button_to " Sign Out", destroy_user_session_path, method: :delete %></p>
    </div>
  </div>
  <div class="container">
    <% flash.each do |flash_type, message| %>
      <div class="alert alert-<%= translate_to_bootstrap flash_type %>">
        <%= message %>
      </div>
    <% end %>
  </div>

  <% end %>

  <%= yield %>

  </div>

</body>
</html>

app/views/queues/dashboard.html.erb
<h1>Airqueuer Dashboard<h1>

<h3>Currently Enqueued Aircraft Summary</h3>

<p class="lead">Aircraft currently queued: <%= @aircraft_count %></p>


<h4>Aircraft by Type</h4>
<table class="table table-striped table-bordered">
  <thead>
    <th>Cargo</th>
    <th>Passenger</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @num_current_cargo %></td>
      <td><%= @num_current_passenger %></td>
    </tr>
  </tbody>
</table>

<h4>Aircraft by Size</h4>
<table class="table table-striped table-bordered">
  <thead>
    <th>Small</th>
    <th>Large</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @num_current_small %></td>
      <td><%= @num_current_large %></td>
    </tr>
  </tbody>
</table>

<div class="btn-toolbar" role="toolbar" aria-label="Manage Planes">
  <div class="btn-group" role="group" aria-label="Enqueue">
    <%=link_to "Enqueue an aircraft", new_aircraft_path, class: "btn btn-success" %>
  </div>
  <div class="btn-group" role="group" aria-label="Dequeue">
    <%= form_tag dequeue_path, method: :delete do %>
    <button class="btn btn-danger">Dequeue an aircraft</button>
    <% end %>
  </div>
</div>

app/views/queues/new.html.erb
<h1>Add an aircraft to the queue</h1>

<%= form_tag enqueue_path, method: :post do %>
<%= label_tag "Aircraft Type: " %>
<%=select_tag :kind, options_for_select(@type_options)  %>

<br>
<%= label_tag "Aircraft Size " %>
<%=select_tag :size, options_for_select(@size_options)  %>
<br>
<button class="btn btn-success">Enqueue Aircraft!</button>
<% end %>